development:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: ram_development
  pool: 5
  username: ram
  password: ram

test:
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: ram_test
  pool: 5
  username: ram
  password: ram

